// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(OpaqueKmpFFI)
import OpaqueKmpFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_opaque_kmp_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_opaque_kmp_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOpaqueKmpInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol LoginStateProtocol: AnyObject, Sendable {
    
    func clear() throws 
    
}
open class LoginState: LoginStateProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_opaque_kmp_fn_clone_loginstate(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_opaque_kmp_fn_free_loginstate(pointer, $0) }
    }

    

    
open func clear()throws   {try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_method_loginstate_clear(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLoginState: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = LoginState

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> LoginState {
        return LoginState(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: LoginState) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LoginState {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: LoginState, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginState_lift(_ pointer: UnsafeMutableRawPointer) throws -> LoginState {
    return try FfiConverterTypeLoginState.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginState_lower(_ value: LoginState) -> UnsafeMutableRawPointer {
    return FfiConverterTypeLoginState.lower(value)
}






public protocol RegistrationStateProtocol: AnyObject, Sendable {
    
    func clear() throws 
    
}
open class RegistrationState: RegistrationStateProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_opaque_kmp_fn_clone_registrationstate(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_opaque_kmp_fn_free_registrationstate(pointer, $0) }
    }

    

    
open func clear()throws   {try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_method_registrationstate_clear(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegistrationState: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = RegistrationState

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> RegistrationState {
        return RegistrationState(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: RegistrationState) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegistrationState {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: RegistrationState, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationState_lift(_ pointer: UnsafeMutableRawPointer) throws -> RegistrationState {
    return try FfiConverterTypeRegistrationState.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationState_lower(_ value: RegistrationState) -> UnsafeMutableRawPointer {
    return FfiConverterTypeRegistrationState.lower(value)
}






/**
 * Owns key material in Rust. Only bytes() makes a foreign-language copy.
 */
public protocol SecretBytesProtocol: AnyObject, Sendable {
    
    func bytes() throws  -> Data
    
    func clear() throws 
    
}
/**
 * Owns key material in Rust. Only bytes() makes a foreign-language copy.
 */
open class SecretBytes: SecretBytesProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_opaque_kmp_fn_clone_secretbytes(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_opaque_kmp_fn_free_secretbytes(pointer, $0) }
    }

    

    
open func bytes()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_method_secretbytes_bytes(self.uniffiClonePointer(),$0
    )
})
}
    
open func clear()throws   {try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_method_secretbytes_clear(self.uniffiClonePointer(),$0
    )
}
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretBytes: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SecretBytes

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SecretBytes {
        return SecretBytes(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SecretBytes) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretBytes {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SecretBytes, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretBytes_lift(_ pointer: UnsafeMutableRawPointer) throws -> SecretBytes {
    return try FfiConverterTypeSecretBytes.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretBytes_lower(_ value: SecretBytes) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSecretBytes.lower(value)
}




public struct Identifiers {
    public var client: Data?
    public var server: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(client: Data?, server: Data?) {
        self.client = client
        self.server = server
    }
}

#if compiler(>=6)
extension Identifiers: Sendable {}
#endif


extension Identifiers: Equatable, Hashable {
    public static func ==(lhs: Identifiers, rhs: Identifiers) -> Bool {
        if lhs.client != rhs.client {
            return false
        }
        if lhs.server != rhs.server {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(client)
        hasher.combine(server)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentifiers: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Identifiers {
        return
            try Identifiers(
                client: FfiConverterOptionData.read(from: &buf), 
                server: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: Identifiers, into buf: inout [UInt8]) {
        FfiConverterOptionData.write(value.client, into: &buf)
        FfiConverterOptionData.write(value.server, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentifiers_lift(_ buf: RustBuffer) throws -> Identifiers {
    return try FfiConverterTypeIdentifiers.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentifiers_lower(_ value: Identifiers) -> RustBuffer {
    return FfiConverterTypeIdentifiers.lower(value)
}


public struct LoginFinishResult {
    public var credentialFinalization: Data
    public var sessionKey: SecretBytes
    public var exportKey: SecretBytes
    public var serverStaticPublicKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(credentialFinalization: Data, sessionKey: SecretBytes, exportKey: SecretBytes, serverStaticPublicKey: Data) {
        self.credentialFinalization = credentialFinalization
        self.sessionKey = sessionKey
        self.exportKey = exportKey
        self.serverStaticPublicKey = serverStaticPublicKey
    }
}

#if compiler(>=6)
extension LoginFinishResult: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLoginFinishResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LoginFinishResult {
        return
            try LoginFinishResult(
                credentialFinalization: FfiConverterData.read(from: &buf), 
                sessionKey: FfiConverterTypeSecretBytes.read(from: &buf), 
                exportKey: FfiConverterTypeSecretBytes.read(from: &buf), 
                serverStaticPublicKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: LoginFinishResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.credentialFinalization, into: &buf)
        FfiConverterTypeSecretBytes.write(value.sessionKey, into: &buf)
        FfiConverterTypeSecretBytes.write(value.exportKey, into: &buf)
        FfiConverterData.write(value.serverStaticPublicKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginFinishResult_lift(_ buf: RustBuffer) throws -> LoginFinishResult {
    return try FfiConverterTypeLoginFinishResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginFinishResult_lower(_ value: LoginFinishResult) -> RustBuffer {
    return FfiConverterTypeLoginFinishResult.lower(value)
}


public struct LoginStartResult {
    public var credentialRequest: Data
    public var clientLoginState: LoginState

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(credentialRequest: Data, clientLoginState: LoginState) {
        self.credentialRequest = credentialRequest
        self.clientLoginState = clientLoginState
    }
}

#if compiler(>=6)
extension LoginStartResult: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLoginStartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LoginStartResult {
        return
            try LoginStartResult(
                credentialRequest: FfiConverterData.read(from: &buf), 
                clientLoginState: FfiConverterTypeLoginState.read(from: &buf)
        )
    }

    public static func write(_ value: LoginStartResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.credentialRequest, into: &buf)
        FfiConverterTypeLoginState.write(value.clientLoginState, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginStartResult_lift(_ buf: RustBuffer) throws -> LoginStartResult {
    return try FfiConverterTypeLoginStartResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginStartResult_lower(_ value: LoginStartResult) -> RustBuffer {
    return FfiConverterTypeLoginStartResult.lower(value)
}


public struct RegistrationFinishResult {
    public var registrationRecord: Data
    public var exportKey: SecretBytes
    public var serverStaticPublicKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(registrationRecord: Data, exportKey: SecretBytes, serverStaticPublicKey: Data) {
        self.registrationRecord = registrationRecord
        self.exportKey = exportKey
        self.serverStaticPublicKey = serverStaticPublicKey
    }
}

#if compiler(>=6)
extension RegistrationFinishResult: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegistrationFinishResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegistrationFinishResult {
        return
            try RegistrationFinishResult(
                registrationRecord: FfiConverterData.read(from: &buf), 
                exportKey: FfiConverterTypeSecretBytes.read(from: &buf), 
                serverStaticPublicKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RegistrationFinishResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.registrationRecord, into: &buf)
        FfiConverterTypeSecretBytes.write(value.exportKey, into: &buf)
        FfiConverterData.write(value.serverStaticPublicKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationFinishResult_lift(_ buf: RustBuffer) throws -> RegistrationFinishResult {
    return try FfiConverterTypeRegistrationFinishResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationFinishResult_lower(_ value: RegistrationFinishResult) -> RustBuffer {
    return FfiConverterTypeRegistrationFinishResult.lower(value)
}


public struct RegistrationStartResult {
    public var registrationRequest: Data
    public var clientRegistrationState: RegistrationState

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(registrationRequest: Data, clientRegistrationState: RegistrationState) {
        self.registrationRequest = registrationRequest
        self.clientRegistrationState = clientRegistrationState
    }
}

#if compiler(>=6)
extension RegistrationStartResult: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegistrationStartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegistrationStartResult {
        return
            try RegistrationStartResult(
                registrationRequest: FfiConverterData.read(from: &buf), 
                clientRegistrationState: FfiConverterTypeRegistrationState.read(from: &buf)
        )
    }

    public static func write(_ value: RegistrationStartResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.registrationRequest, into: &buf)
        FfiConverterTypeRegistrationState.write(value.clientRegistrationState, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationStartResult_lift(_ buf: RustBuffer) throws -> RegistrationStartResult {
    return try FfiConverterTypeRegistrationStartResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationStartResult_lower(_ value: RegistrationStartResult) -> RustBuffer {
    return FfiConverterTypeRegistrationStartResult.lower(value)
}


public enum OpaqueError: Swift.Error {

    
    
    case InvalidMessage
    case AuthenticationFailed
    case StateConsumed
    case ProtocolFailure
    case InvalidBase64
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOpaqueError: FfiConverterRustBuffer {
    typealias SwiftType = OpaqueError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OpaqueError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidMessage
        case 2: return .AuthenticationFailed
        case 3: return .StateConsumed
        case 4: return .ProtocolFailure
        case 5: return .InvalidBase64

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OpaqueError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidMessage:
            writeInt(&buf, Int32(1))
        
        
        case .AuthenticationFailed:
            writeInt(&buf, Int32(2))
        
        
        case .StateConsumed:
            writeInt(&buf, Int32(3))
        
        
        case .ProtocolFailure:
            writeInt(&buf, Int32(4))
        
        
        case .InvalidBase64:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpaqueError_lift(_ buf: RustBuffer) throws -> OpaqueError {
    return try FfiConverterTypeOpaqueError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOpaqueError_lower(_ value: OpaqueError) -> RustBuffer {
    return FfiConverterTypeOpaqueError.lower(value)
}


extension OpaqueError: Equatable, Hashable {}




extension OpaqueError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeIdentifiers: FfiConverterRustBuffer {
    typealias SwiftType = Identifiers?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeIdentifiers.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeIdentifiers.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
public func base64UrlDecode(encoded: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_func_base64_url_decode(
        FfiConverterString.lower(encoded),$0
    )
})
}
public func base64UrlEncode(bytes: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_opaque_kmp_fn_func_base64_url_encode(
        FfiConverterData.lower(bytes),$0
    )
})
}
public func clientLoginFinish(password: Data, clientLoginState: LoginState, credentialResponse: Data, identifiers: Identifiers?)throws  -> LoginFinishResult  {
    return try  FfiConverterTypeLoginFinishResult_lift(try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_func_client_login_finish(
        FfiConverterData.lower(password),
        FfiConverterTypeLoginState_lower(clientLoginState),
        FfiConverterData.lower(credentialResponse),
        FfiConverterOptionTypeIdentifiers.lower(identifiers),$0
    )
})
}
public func clientLoginStart(password: Data)throws  -> LoginStartResult  {
    return try  FfiConverterTypeLoginStartResult_lift(try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_func_client_login_start(
        FfiConverterData.lower(password),$0
    )
})
}
public func clientRegistrationFinish(password: Data, clientRegistrationState: RegistrationState, registrationResponse: Data, identifiers: Identifiers?)throws  -> RegistrationFinishResult  {
    return try  FfiConverterTypeRegistrationFinishResult_lift(try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_func_client_registration_finish(
        FfiConverterData.lower(password),
        FfiConverterTypeRegistrationState_lower(clientRegistrationState),
        FfiConverterData.lower(registrationResponse),
        FfiConverterOptionTypeIdentifiers.lower(identifiers),$0
    )
})
}
public func clientRegistrationStart(password: Data)throws  -> RegistrationStartResult  {
    return try  FfiConverterTypeRegistrationStartResult_lift(try rustCallWithError(FfiConverterTypeOpaqueError_lift) {
    uniffi_opaque_kmp_fn_func_client_registration_start(
        FfiConverterData.lower(password),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_opaque_kmp_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_opaque_kmp_checksum_func_base64_url_decode() != 38611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_func_base64_url_encode() != 53957) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_func_client_login_finish() != 31386) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_func_client_login_start() != 42873) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_func_client_registration_finish() != 64932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_func_client_registration_start() != 50751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_method_loginstate_clear() != 35669) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_method_registrationstate_clear() != 20790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_method_secretbytes_bytes() != 59387) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_kmp_checksum_method_secretbytes_clear() != 62880) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOpaqueKmpInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all